app:
  env: dev
  name: go-mall
  log:
    path: "/tmp/applog/go-mall.log"
    max_size: 100
    max_age: 60
database:
  type: mysql
  dsn: reserved
  maxopenconn: 100
  maxidleconn: 10
  maxlifetime: 300
